### PR TITLE
Fix issue with build element

### PR DESCRIPTION
**Pull request by brunowego**
Simple fix to work with [Parsley](http://parsleyjs.org/).

```js
this.$element.before(this.$container);
```

### CODE REVIEW

**Comment by lucknerjb** [comment]
Why exactly is this change needed? What was the issue you were facing before? Thanks for the PR btw

**Comment by brunowego** [comment]
I not know exactly why, but this simple change works when use Parsley.

test

**Comment by lucknerjb** [comment]
Hmm, thanks for the vid. I'll have a quick look and make sure there are no
issues with the PR and I'll merge it later tonight

**Comment by brunowego** [comment]
Thanks a lot @lucknerjb :+1:

**Comment by brunowego** [comment]
@lucknerjb you will merge it? Thanks.

**Comment by lucknerjb** [comment]
@brunowego Sorry for the delay mate. Had a quick look as promised and merged it!

**Comment by brunowego** [comment]
Thanks @lucknerjb :+1:

**Pull request merged**
