### PR TITLE
Pass options to typeahead.js

### PR DESCRIPTION
**Pull request by dhendo**
Allow options to be passed to the typeahead.js instance (e.g. minLength)

### CODE REVIEW

**Comment by tom-dignan** [comment]
This seems like the best solution to the problem. 
Please merge this. +1

**Comment by dhendo** [comment]
@timschlechter Any chance of a merge?

**Comment by Kha** [comment]
It's already been possible to pass options since 145c00cd9, so now there are two different ways to do the same thing...

**Comment by dhendo** [comment]
@Kha @lucknerjb You're right - looks like another way of doing this was added in the meantime. If you guys are OK with it, I'll re-open the PR and back-out my changes? There's no good reason to have more than one way of doing things.

**Comment by lucknerjb** [comment]
@dhendo @Kha You guys are correct. My mistake - I've merged in the PR and will get it pushed out with the next release :)

**Pull request merged**
